name: Buikd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Fetch the source code from the repository
    - name: Checkout sources
      uses: actions/checkout@v4

    # 2. Install and configure the specified Java JDK version
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '35'
        distribution: 'open-jdk'

    # 3. Configure Gradle, validate the wrapper, and enable automatic caching
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # 4. Compile the application and execute all test suites
    - name: Build with Gradle
      run: ./gradlew clean build
